export const
  effect= Symbol.for("stateful-function:effect"),
  Effect= effect,
  effectCleanup= Symbol.for("stateful-function:effect-cleanup"),
  EffectCleanup= effectCleanup,
  effectCleanupPending= Symbol.for("stateful-function:effect-cleanup-pending"),
  EffectCleanupPending= effectCleanupPending,
  context= Symbol.for("stateful-function:context"),
  Context= context,
  contextValue= Symbol.for("stateful-function:context-value"),
  ContextValue= contextValue
