export const
  effect= Symbol.for("stateful-function:effect"),
  Effect= effect,
  effectCleanup= Symbol.for("stateful-function:effect-cleanup"),
  EffectCleanup= effectCleanup,
  context= Symbol.for("stateful-function:context"),
  Context= context,
  contextValue= Symbol.for("stateful-function:context-value"),
  ContextValue= contextValue,
  rerender= Symbol.for("stateful-function:rerender"),
  Rerender= rerender,
  args= Symbol.for("stateful-function:args"),
  Args= args
